events {}

http {

    upstream blue_backend {
        server blue:3000;
    }

    upstream green_backend {
        server green:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://green_backend;
        }
    }
}